//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopMVC.WebShopWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model.PersonDTO", Namespace="http://schemas.datacontract.org/2004/07/WebShopWCF")]
    [System.SerializableAttribute()]
    public partial class ModelPersonDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelPersonDTO.Admin AdminsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelOrderDTO[] OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelPersonDTO.Admin Admins {
            get {
                return this.AdminsField;
            }
            set {
                if ((this.AdminsField.Equals(value) != true)) {
                    this.AdminsField = value;
                    this.RaisePropertyChanged("Admins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelOrderDTO[] Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.FlagsAttribute()]
        [System.Runtime.Serialization.DataContractAttribute(Name="Model.PersonDTO.Admin", Namespace="http://schemas.datacontract.org/2004/07/WebShopWCF")]
        public enum Admin : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            User = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute(Value="Admin")]
            AdminMember = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model.OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/WebShopWCF")]
    [System.SerializableAttribute()]
    public partial class ModelOrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelOrderProductDTO[] OrderProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelPersonDTO PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelOrderProductDTO[] OrderProduct {
            get {
                return this.OrderProductField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderProductField, value) != true)) {
                    this.OrderProductField = value;
                    this.RaisePropertyChanged("OrderProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelPersonDTO Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model.OrderProductDTO", Namespace="http://schemas.datacontract.org/2004/07/WebShopWCF")]
    [System.SerializableAttribute()]
    public partial class ModelOrderProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelKonsolDTO KonsolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KonsolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelOrderDTO OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelProductDTO ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelKonsolDTO Konsol {
            get {
                return this.KonsolField;
            }
            set {
                if ((object.ReferenceEquals(this.KonsolField, value) != true)) {
                    this.KonsolField = value;
                    this.RaisePropertyChanged("Konsol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KonsolId {
            get {
                return this.KonsolIdField;
            }
            set {
                if ((this.KonsolIdField.Equals(value) != true)) {
                    this.KonsolIdField = value;
                    this.RaisePropertyChanged("KonsolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelOrderDTO Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderProductId {
            get {
                return this.OrderProductIdField;
            }
            set {
                if ((this.OrderProductIdField.Equals(value) != true)) {
                    this.OrderProductIdField = value;
                    this.RaisePropertyChanged("OrderProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelProductDTO Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model.KonsolDTO", Namespace="http://schemas.datacontract.org/2004/07/WebShopWCF")]
    [System.SerializableAttribute()]
    public partial class ModelKonsolDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelOrderProductDTO[] OrderProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelProductDTO[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsoleName {
            get {
                return this.ConsoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsoleNameField, value) != true)) {
                    this.ConsoleNameField = value;
                    this.RaisePropertyChanged("ConsoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelOrderProductDTO[] OrderProduct {
            get {
                return this.OrderProductField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderProductField, value) != true)) {
                    this.OrderProductField = value;
                    this.RaisePropertyChanged("OrderProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelProductDTO[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model.ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/WebShopWCF")]
    [System.SerializableAttribute()]
    public partial class ModelProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelGenreDTO[] GenresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelKonsolDTO[] KonsolsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelOrderProductDTO[] OrderProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PicLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearOfReleaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelGenreDTO[] Genres {
            get {
                return this.GenresField;
            }
            set {
                if ((object.ReferenceEquals(this.GenresField, value) != true)) {
                    this.GenresField = value;
                    this.RaisePropertyChanged("Genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelKonsolDTO[] Konsols {
            get {
                return this.KonsolsField;
            }
            set {
                if ((object.ReferenceEquals(this.KonsolsField, value) != true)) {
                    this.KonsolsField = value;
                    this.RaisePropertyChanged("Konsols");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelOrderProductDTO[] OrderProduct {
            get {
                return this.OrderProductField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderProductField, value) != true)) {
                    this.OrderProductField = value;
                    this.RaisePropertyChanged("OrderProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PicLocation {
            get {
                return this.PicLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PicLocationField, value) != true)) {
                    this.PicLocationField = value;
                    this.RaisePropertyChanged("PicLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearOfRelease {
            get {
                return this.YearOfReleaseField;
            }
            set {
                if ((this.YearOfReleaseField.Equals(value) != true)) {
                    this.YearOfReleaseField = value;
                    this.RaisePropertyChanged("YearOfRelease");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model.GenreDTO", Namespace="http://schemas.datacontract.org/2004/07/WebShopWCF")]
    [System.SerializableAttribute()]
    public partial class ModelGenreDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebShopMVC.WebShopWCF.ModelProductDTO[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenreName {
            get {
                return this.GenreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreNameField, value) != true)) {
                    this.GenreNameField = value;
                    this.RaisePropertyChanged("GenreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebShopMVC.WebShopWCF.ModelProductDTO[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebShopWCF.IWebShop")]
    public interface IWebShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/Register", ReplyAction="http://tempuri.org/IWebShop/RegisterResponse")]
        void Register(WebShopMVC.WebShopWCF.ModelPersonDTO person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/Register", ReplyAction="http://tempuri.org/IWebShop/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(WebShopMVC.WebShopWCF.ModelPersonDTO person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/GetOrderList", ReplyAction="http://tempuri.org/IWebShop/GetOrderListResponse")]
        WebShopMVC.WebShopWCF.ModelOrderDTO[] GetOrderList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/GetOrderList", ReplyAction="http://tempuri.org/IWebShop/GetOrderListResponse")]
        System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelOrderDTO[]> GetOrderListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/FindUser", ReplyAction="http://tempuri.org/IWebShop/FindUserResponse")]
        WebShopMVC.WebShopWCF.ModelPersonDTO FindUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/FindUser", ReplyAction="http://tempuri.org/IWebShop/FindUserResponse")]
        System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelPersonDTO> FindUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/GetAllConsoles", ReplyAction="http://tempuri.org/IWebShop/GetAllConsolesResponse")]
        WebShopMVC.WebShopWCF.ModelKonsolDTO[] GetAllConsoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/GetAllConsoles", ReplyAction="http://tempuri.org/IWebShop/GetAllConsolesResponse")]
        System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelKonsolDTO[]> GetAllConsolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/GetAllGenres", ReplyAction="http://tempuri.org/IWebShop/GetAllGenresResponse")]
        WebShopMVC.WebShopWCF.ModelGenreDTO[] GetAllGenres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShop/GetAllGenres", ReplyAction="http://tempuri.org/IWebShop/GetAllGenresResponse")]
        System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelGenreDTO[]> GetAllGenresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebShopChannel : WebShopMVC.WebShopWCF.IWebShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebShopClient : System.ServiceModel.ClientBase<WebShopMVC.WebShopWCF.IWebShop>, WebShopMVC.WebShopWCF.IWebShop {
        
        public WebShopClient() {
        }
        
        public WebShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Register(WebShopMVC.WebShopWCF.ModelPersonDTO person) {
            base.Channel.Register(person);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(WebShopMVC.WebShopWCF.ModelPersonDTO person) {
            return base.Channel.RegisterAsync(person);
        }
        
        public WebShopMVC.WebShopWCF.ModelOrderDTO[] GetOrderList() {
            return base.Channel.GetOrderList();
        }
        
        public System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelOrderDTO[]> GetOrderListAsync() {
            return base.Channel.GetOrderListAsync();
        }
        
        public WebShopMVC.WebShopWCF.ModelPersonDTO FindUser(string userName) {
            return base.Channel.FindUser(userName);
        }
        
        public System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelPersonDTO> FindUserAsync(string userName) {
            return base.Channel.FindUserAsync(userName);
        }
        
        public WebShopMVC.WebShopWCF.ModelKonsolDTO[] GetAllConsoles() {
            return base.Channel.GetAllConsoles();
        }
        
        public System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelKonsolDTO[]> GetAllConsolesAsync() {
            return base.Channel.GetAllConsolesAsync();
        }
        
        public WebShopMVC.WebShopWCF.ModelGenreDTO[] GetAllGenres() {
            return base.Channel.GetAllGenres();
        }
        
        public System.Threading.Tasks.Task<WebShopMVC.WebShopWCF.ModelGenreDTO[]> GetAllGenresAsync() {
            return base.Channel.GetAllGenresAsync();
        }
    }
}
